/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.LOCAL.ConnPostgres;
import Evento.Color.cla_color_pelete;
import Evento.Combobox.EvenCombobox;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import FORMULARIO.BO.*;
import FORMULARIO.DAO.*;
import FORMULARIO.ENTIDAD.*;
import java.sql.Connection;

/**
 *
 * @author Digno
 */
public class FrmDato_Banco extends javax.swing.JInternalFrame {

    EvenJFRAME evejfr = new EvenJFRAME();
    EvenJtable evetb = new EvenJtable();
    dato_banco unid = new dato_banco();
    BO_dato_banco uBO = new BO_dato_banco();
    DAO_dato_banco udao = new DAO_dato_banco();
    banco dban = new banco();
    BO_banco dbBO = new BO_banco();
    DAO_banco dbdao = new DAO_banco();
    EvenCombobox evecmb = new EvenCombobox();
    EvenJTextField evejtf = new EvenJTextField();
    Connection conn = ConnPostgres.getConnPosgres();
    cla_color_pelete clacolor= new cla_color_pelete();
    private int fk_idbanco;
    private boolean hab_carga_banco;
    
    void abrir_formulario() {
        this.setTitle("DATO BANCO");
        evejfr.centrar_formulario_internalframa(this);        
        reestableser();
        udao.actualizar_tabla_dato_banco(conn, tblpro_unidad);
        color_formulario();
        cargar_banco();
    }
    void cargar_banco(){
        evecmb.cargarCombobox(conn, cmbbanco,"idbanco","nombre","banco","");
        hab_carga_banco=true;
    }
    void color_formulario(){
        panel_tabla_unidad.setBackground(clacolor.getColor_tabla());
        panel_insertar_unidad.setBackground(clacolor.getColor_insertar_primario());
    }
    boolean validar_guardar() {
        if (evejtf.getBoo_JTextField_vacio(txttitular, "DEBE CARGAR UN TITULAR")) {
            return false;
        }
        if (evejtf.getBoo_JTextField_vacio(txtdocumento, "DEBE CARGAR UN DOCUMENTO")) {
            return false;
        }
        if (evejtf.getBoo_JTextField_vacio(txtnrocuenta, "DEBE CARGAR UN NRO CUENTA")) {
            return false;
        }
        return true;
    }

    void boton_guardar() {
        if (validar_guardar()) {
            unid.setC2titular(txttitular.getText());
            unid.setC3documento(txtdocumento.getText());
            unid.setC4nro_cuenta(txtnrocuenta.getText());
            unid.setC5mibanco(jCmicuenta.isSelected());
            unid.setC6fk_idbanco(fk_idbanco);
            uBO.insertar_dato_banco(unid, tblpro_unidad);
            reestableser();
        }
    }

    void boton_editar() {
        if (validar_guardar()) {
            unid.setC1iddato_banco(Integer.parseInt(txtid.getText()));
            unid.setC2titular(txttitular.getText());
            unid.setC3documento(txtdocumento.getText());
            unid.setC4nro_cuenta(txtnrocuenta.getText());
            unid.setC5mibanco(jCmicuenta.isSelected());
            unid.setC6fk_idbanco(fk_idbanco);
            uBO.update_dato_banco(unid, tblpro_unidad);
        }
    }

    void seleccionar_tabla() {
        int iddato_banco=evetb.getInt_select_id(tblpro_unidad);
        udao.cargar_dato_banco(conn, unid, iddato_banco);
        txtid.setText(String.valueOf(unid.getC1iddato_banco()));
        txttitular.setText(unid.getC2titular());
        txtdocumento.setText(unid.getC3documento());
        txtnrocuenta.setText(unid.getC4nro_cuenta());
        jCmicuenta.setSelected(unid.getC5mibanco());
        dbdao.cargar_banco(conn, dban,unid.getC6fk_idbanco());
        cmbbanco.setSelectedItem("("+dban.getC1idbanco()+")-"+dban.getC2nombre());
        btnguardar.setEnabled(false);
        btneditar.setEnabled(true);
    }
    void reestableser(){
        txtid.setText(null);
        txttitular.setText(null);
        txtdocumento.setText(null);
        txtnrocuenta.setText(null);
        jCmicuenta.setSelected(false);
        fk_idbanco=0;
        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);
        btndeletar.setEnabled(false);
        txttitular.grabFocus();
    }
    void boton_nuevo(){
        reestableser();
    }
    public FrmDato_Banco() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_insertar_unidad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttitular = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtdocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnrocuenta = new javax.swing.JTextField();
        jCmicuenta = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cmbbanco = new javax.swing.JComboBox<>();
        panel_tabla_unidad = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpro_unidad = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        panel_insertar_unidad.setBackground(new java.awt.Color(153, 204, 255));
        panel_insertar_unidad.setBorder(javax.swing.BorderFactory.createTitledBorder("CREAR DATO"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(204, 204, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("TITULAR:");

        txttitular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttitular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttitularKeyPressed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/nuevo.png"))); // NOI18N
        btnnuevo.setText("NUEVO");
        btnnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/guardar.png"))); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/modificar.png"))); // NOI18N
        btneditar.setText("EDITAR");
        btneditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btndeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/eliminar.png"))); // NOI18N
        btndeletar.setText("DELETAR");
        btndeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndeletar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("DOCUMENTO:");

        txtdocumento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdocumentoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("NRO CUENTA:");

        txtnrocuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnrocuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnrocuentaKeyPressed(evt);
            }
        });

        jCmicuenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCmicuenta.setText("MI CUENTA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("BANCO:");

        cmbbanco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbbanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbbanco.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbbancoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel_insertar_unidadLayout = new javax.swing.GroupLayout(panel_insertar_unidad);
        panel_insertar_unidad.setLayout(panel_insertar_unidadLayout);
        panel_insertar_unidadLayout.setHorizontalGroup(
            panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                        .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttitular)
                            .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 205, Short.MAX_VALUE))))
                    .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdocumento))
                    .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                                .addComponent(jCmicuenta)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtnrocuenta)))
                    .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                        .addComponent(btnnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndeletar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(61, 61, 61)
                        .addComponent(cmbbanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_insertar_unidadLayout.setVerticalGroup(
            panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_insertar_unidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txttitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnrocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmicuenta)
                .addGap(8, 8, 8)
                .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(cmbbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_insertar_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnuevo)
                    .addComponent(btnguardar)
                    .addComponent(btneditar)
                    .addComponent(btndeletar))
                .addContainerGap())
        );

        panel_tabla_unidad.setBackground(new java.awt.Color(51, 204, 255));
        panel_tabla_unidad.setBorder(javax.swing.BorderFactory.createTitledBorder("TABLA"));

        tblpro_unidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpro_unidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblpro_unidadMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblpro_unidad);

        javax.swing.GroupLayout panel_tabla_unidadLayout = new javax.swing.GroupLayout(panel_tabla_unidad);
        panel_tabla_unidad.setLayout(panel_tabla_unidadLayout);
        panel_tabla_unidadLayout.setHorizontalGroup(
            panel_tabla_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        panel_tabla_unidadLayout.setVerticalGroup(
            panel_tabla_unidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tabla_unidadLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_insertar_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_tabla_unidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_tabla_unidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_insertar_unidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        boton_guardar();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        udao.ancho_tabla_dato_banco(tblpro_unidad);
    }//GEN-LAST:event_formInternalFrameOpened

    private void tblpro_unidadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpro_unidadMouseReleased
        // TODO add your handling code here:
        seleccionar_tabla();
    }//GEN-LAST:event_tblpro_unidadMouseReleased

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        boton_editar();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
        boton_nuevo();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txttitularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttitularKeyPressed
        // TODO add your handling code here:
//        evejtf.saltar_campo_enter(evt, txtnombre, txtprecio_venta);
    }//GEN-LAST:event_txttitularKeyPressed

    private void txtdocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocumentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentoKeyPressed

    private void txtnrocuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnrocuentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnrocuentaKeyPressed

    private void cmbbancoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbbancoItemStateChanged
        // TODO add your handling code here:
        if(hab_carga_banco){
        fk_idbanco=evecmb.getInt_seleccionar_COMBOBOX(conn, cmbbanco, "idbanco", "nombre", "banco");
        }
    }//GEN-LAST:event_cmbbancoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> cmbbanco;
    private javax.swing.JCheckBox jCmicuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_insertar_unidad;
    private javax.swing.JPanel panel_tabla_unidad;
    private javax.swing.JTable tblpro_unidad;
    private javax.swing.JTextField txtdocumento;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnrocuenta;
    private javax.swing.JTextField txttitular;
    // End of variables declaration//GEN-END:variables
}
