/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.LOCAL.ConnPostgres;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import FORMULARIO.ENTIDAD.venta;
import IMPRESORA_POS.PosImprimir_Venta;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;

/**
 *
 * @author Digno
 */
public class JDpago_combinado extends javax.swing.JDialog {

    venta ven = new venta();
//    PosImprimir_Venta posv = new PosImprimir_Venta();
    Connection connLocal = null;
    ConnPostgres cpt = new ConnPostgres();
    EvenJTextField evejtf = new EvenJTextField();
    EvenJFRAME evetbl = new EvenJFRAME();
    private String forma_pago_COMBINADO = "COMBINADO";
    private String tabla_origen_COMBINADO = "VENTA_COMBI";
    void abrir_formulario() {
        this.setTitle("PAGO COMBINADO");
        connLocal = cpt.getConnPosgres();
        evetbl.centrar_formulario_JDialog(this);
        jFtotal_pagar.setValue(ven.getMonto_ventaGlobal());
        txtpagado_efectivo.setText(evejtf.getString_format_nro_decimal(ven.getMonto_ventaGlobal()));
        txtpagado_tarjeta.setText("0");
        txtpagado_efectivo.grabFocus();
    }

    private void calcular_en_pago_efectivo() {
        if(txtpagado_efectivo.getText().trim().length()==0){
            txtpagado_efectivo.setText("0");
        }
        double pagado_efectivo = evejtf.getDouble_format_nro_entero(txtpagado_efectivo);
        double diferencia_tarjeta = ven.getMonto_ventaGlobal() - pagado_efectivo;
        if (diferencia_tarjeta >= 0) {
            txtpagado_tarjeta.setText(evejtf.getString_format_nro_decimal(diferencia_tarjeta));
            FrmVenta.ven.setC8forma_pago(forma_pago_COMBINADO);
            FrmVenta.ven.setC3monto_venta_efectivo(pagado_efectivo);
            FrmVenta.ven.setC14monto_venta_tarjeta(diferencia_tarjeta);
            FrmVenta.caja.setC4monto_venta_efectivo(pagado_efectivo);
            FrmVenta.caja.setC5monto_venta_tarjeta(diferencia_tarjeta);
            FrmVenta.caja.setC13tabla_origen(tabla_origen_COMBINADO);
        } else {
            txtpagado_efectivo.setText(evejtf.getString_format_nro_decimal(ven.getMonto_ventaGlobal()));
            txtpagado_tarjeta.setText("0");
        }
    }
    private void calcular_en_pago_tarjeta() {
        if(txtpagado_tarjeta.getText().trim().length()==0){
            txtpagado_tarjeta.setText("0");
        }
        double pagado_tarjeta = evejtf.getDouble_format_nro_entero(txtpagado_tarjeta);
        double diferencia_efectivo = ven.getMonto_ventaGlobal() - pagado_tarjeta;
        if (diferencia_efectivo >= 0) {
            txtpagado_efectivo.setText(evejtf.getString_format_nro_decimal(diferencia_efectivo));
            FrmVenta.ven.setC8forma_pago(forma_pago_COMBINADO);
            FrmVenta.ven.setC3monto_venta_efectivo(diferencia_efectivo);
            FrmVenta.ven.setC14monto_venta_tarjeta(pagado_tarjeta);
            FrmVenta.caja.setC4monto_venta_efectivo(diferencia_efectivo);
            FrmVenta.caja.setC5monto_venta_tarjeta(pagado_tarjeta);
            FrmVenta.caja.setC13tabla_origen(tabla_origen_COMBINADO);
        } else {
            txtpagado_tarjeta.setText(evejtf.getString_format_nro_decimal(ven.getMonto_ventaGlobal()));
            txtpagado_efectivo.setText("0");
        }
    }
    private void boton_cerrar(){
        this.dispose();
    }
    public JDpago_combinado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFtotal_pagar = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpagado_efectivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpagado_tarjeta = new javax.swing.JTextField();
        btncerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jFtotal_pagar.setEditable(false);
        jFtotal_pagar.setBackground(new java.awt.Color(255, 255, 204));
        jFtotal_pagar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        jFtotal_pagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFtotal_pagar.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jFtotal_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFtotal_pagarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TOTAL A PAGAR:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("PAGADO EFECTIVO:");

        txtpagado_efectivo.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        txtpagado_efectivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpagado_efectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpagado_efectivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpagado_efectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpagado_efectivoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("PAGADO TARJETA:");

        txtpagado_tarjeta.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        txtpagado_tarjeta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpagado_tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpagado_tarjetaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpagado_tarjetaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpagado_tarjetaKeyTyped(evt);
            }
        });

        btncerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncerrar.setText("CERRAR");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta/efectivo.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta/credito.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFtotal_pagar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpagado_efectivo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpagado_tarjeta, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFtotal_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpagado_efectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(txtpagado_tarjeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFtotal_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFtotal_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFtotal_pagarActionPerformed

    private void txtpagado_efectivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagado_efectivoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boton_cerrar();
        }
    }//GEN-LAST:event_txtpagado_efectivoKeyPressed

    private void txtpagado_efectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagado_efectivoKeyReleased
        // TODO add your handling code here:
//        calcular_vuelto();
        calcular_en_pago_efectivo();
    }//GEN-LAST:event_txtpagado_efectivoKeyReleased

    private void txtpagado_efectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagado_efectivoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagado_efectivoKeyTyped

    private void txtpagado_tarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagado_tarjetaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boton_cerrar();
        }
    }//GEN-LAST:event_txtpagado_tarjetaKeyPressed

    private void txtpagado_tarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagado_tarjetaKeyReleased
        // TODO add your handling code here:
        calcular_en_pago_tarjeta();
    }//GEN-LAST:event_txtpagado_tarjetaKeyReleased

    private void txtpagado_tarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpagado_tarjetaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpagado_tarjetaKeyTyped

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        boton_cerrar();
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDpago_combinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDpago_combinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDpago_combinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDpago_combinado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDpago_combinado dialog = new JDpago_combinado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JFormattedTextField jFtotal_pagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtpagado_efectivo;
    private javax.swing.JTextField txtpagado_tarjeta;
    // End of variables declaration//GEN-END:variables
}
